#My first learning docker container
FROM alpine:3.17
ENV ADMIN_USER="swamy"

USER root

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
ENV PATH=$PATH:$JAVA_HOME/bin

ARG MAVEN_VERSION=3.9.2
ARG USER_HOME_DIR="/root"
ARG MAVEN_BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

 
RUN { \
      echo '#!/bin/sh'; \
      echo 'set -e'; \
      echo; \
      echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
   } > /usr/local/bin/docker-java-home \
   && chmod +x /usr/local/bin/docker-java-home
   
RUN set -x && \
  apk add --no-cache curl libc6-compat && \
  apk add --no-cache openjdk8 && \
  [ "$JAVA_HOME" = "$(docker-java-home)" ] && \
  apk --no-cache add shadow && \
  apk --no-cache add sudo && \
  apk --no-cache add curl && \
  apk --no-cache add git
	
# download,unzip,and creates symbolic link for maven
RUN sudo mkdir -p usr/share/maven usr/share/maven/ref \
	&& curl -fsSL -o /tmp/apache-maven.tar.gz  ${MAVEN_BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
	&& tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
	&& rm -f /tmp/apache-maven.tar.gz \
	&& ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME=/usr/share/maven
ENV MAVEN_CONFIG=${USER_HOME_DIR}/.m2

# adds/copies the Dockerfile to Myfiles folder
ADD Dockerfile /MyFiles
RUN ls /MyFiles

# adds/copies the Dockerfile to MyTestFiles folder
COPY Dockerfile /MyTestFiles
RUN ls /MyTestFiles

RUN mkdir -p /var/workspace/MyLearning 
RUN git clone https://swamyraj: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@github.com/swamyraj/MyLearning.git "/var/workspace/MyLearning"
RUN pwd
RUN ls
RUN ls /var/workspace
RUN cd /var/workspace/MyLearning
RUN pwd
RUN ls
#RUN git checkout master
RUN mvn -B -f /var/workspace/MyLearning/demo/pom.xml clean package -Dmaven.test.skip=true -pl com.example:demo -am spring-boot:repackage
RUN adduser -D MyLearningUser && \
	usermod -aG root MyLearningUser && \
	echo "MyLearningUser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
	chmod 777 /var/workspace/MyLearning/demo/target/demo-0.0.1-SNAPSHOT.jar

USER MyLearningUser

EXPOSE 8080

CMD java -jar /var/workspace/MyLearning/demo/target/demo-0.0.1-SNAPSHOT.jar

#CMD ["/bin/sh"]



